# -*- coding: utf-8 -*-
"""Movie_interest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhvcqvcyNoTweRd5iUlMyrumjPdv0n1_

# **ML with Movie info Dataset**
"""

import pandas as pd
movies = pd.read_csv('/Movie Interests.csv')
movies

movies.duplicated().sum()

input_data = movies.drop(columns=['Interest'])

movies.shape

input_data

output_data = movies['Interest']

output_data

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(input_data,output_data)
model. predict([[9,1]])

